# Generated by Django 3.2.5 on 2021-07-12 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('TA', 'TA')], help_text='Role', max_length=10, null=True)),
                ('course', models.CharField(blank=True, choices=[('code201', 'code201'), ('code301', 'code301'), ('code401_python', 'code401_python'), ('code401_java', 'code401_java'), ('code401_javaScript', 'code401_javaScript')], help_text='Course', max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
