# Generated by Django 3.2.5 on 2021-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(default='pending ticket', max_length=256),
        ),
    ]
